# Site settings
title: Tracy Web Technologies
logo: "/images/tracy-azul.png"
email: contato@tracy.com.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  TracyWebTech

# Build settings
markdown: kramdown
